/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sleepyduck;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author MetcalfPriv
 */
public class ColorsPreview extends javax.swing.JPanel {

	private Color color;
	private final int grid = 8;

	/**
	 * Creates new form ColorsPreview
	 */
	public ColorsPreview() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

	public void setColor(Color color) {
		this.color = color;
		repaint();
	}

	@Override
	public void paint(Graphics graphics) {
		for (int x = 0; x < getWidth(); x += grid) {
			for (int y = 0; y < getHeight(); y += grid) {
				graphics.setColor(((x+y)/grid) % 2 == 1 ? Color.LIGHT_GRAY : Color.WHITE);
				graphics.fillRect(x, y, getWidth(), getHeight());
			}
		}
		if (color != null) {
			graphics.setColor(color);
			graphics.fillRect(0, 0, getWidth(), getHeight());
		}
	}
}
