/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sleepyduck;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.plaf.BorderUIResource;

/**
 *
 * @author MetcalfPriv
 */
public class CuffColor extends javax.swing.JPanel {

	private boolean _isBeadSelected;
	private boolean _isYarnSelected;
	private int _borderThickness = 2;
	private int _defaultSize = 8;

	public CuffColor() {
		setIsYarnSelected(false);
		setIsBeadSelected(false);
		setColor(Color.WHITE);
	}

	public void setIsBeadSelected(boolean b) {
		_isBeadSelected = b;
		repaint();
	}

	public void setIsYarnSelected(boolean b) {
		_isYarnSelected = b;
		setBorder(new BorderUIResource.LineBorderUIResource(b ? Color.BLACK : getBackground(), _borderThickness));
	}

	@Override
	public void paint(Graphics graphics) {
		super.paint(graphics);
		if (_isBeadSelected) {
			graphics.setColor(Color.BLACK);
			graphics.drawOval(getWidth() / 2 - 4, getHeight() / 2 - 4, 7, 7);
		}
	}
	
	@Override
	public Dimension getSize() {
		return getPreferredSize();
	}

	@Override
	public Dimension getPreferredSize() {
		return new Dimension(_defaultSize + _borderThickness*2, _defaultSize + _borderThickness*2);
	}

	public void setColor(Color color) {
		setBackground(color);
		setBorder(new BorderUIResource.LineBorderUIResource(_isYarnSelected ? Color.BLACK : color, _borderThickness));
	}

	@Override
	public String toString() {
		return getToolTipText();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
