/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sleepyduck;

import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.ParsingException;
import nu.xom.Serializer;

/**
 *
 * @author MetcalfPriv
 */
public class CuffMain extends javax.swing.JFrame {

	private JFileChooser fileChooser;
	private Preferences preferences;
	private Object CuffTab;

	/**
	 * Creates new form MuddarFrame
	 */
	public CuffMain() {
		initComponents();
		preferences = new Preferences(colors, jTabbedPaneCuffs);
		fileChooser = new JFileChooser();
		fileChooser.resetChoosableFileFilters();
		fileChooser.setFileFilter(new FileNameExtensionFilter("XML", new String[]{"xml"}));
	}

	private void saveToFile(File theFileToSave, CuffTab cuffTab) {
		Element saveData = cuffTab.save();
		if (fileChooser.getSelectedFile() != null) {
			try {
				Document doc = new Document(saveData);
				Serializer serializer = new Serializer(new FileOutputStream(theFileToSave), "ISO-8859-1");
				serializer.setIndent(4);
				serializer.setMaxLength(64);
				serializer.write(doc);
			} catch (IOException ex) {
				Logger.getLogger(CuffMain.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPaneCuffs = new javax.swing.JTabbedPane();
        cuffTab1 = new net.sleepyduck.CuffTab();
        colors = new net.sleepyduck.Colors();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemCreateTab = new javax.swing.JMenuItem();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemCreateCuff = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPreferences = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jTabbedPaneCuffs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabbedPaneCuffs.addTab("Tab 1", cuffTab1);

        jMenuFile.setText("File");

        jMenuItemCreateTab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCreateTab.setText("New");
        jMenuItemCreateTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateTabActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemCreateTab);

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSaveAs.setText("Save As");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItemClose.setText("Close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemCreateCuff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCreateCuff.setText("New Cuff");
        jMenuItemCreateCuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateCuffActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCreateCuff);
        jMenuEdit.add(jSeparator2);

        jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUndo.setText("Undo");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemUndo);

        jMenuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRedo.setText("Redo");
        jMenuItemRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemRedo);
        jMenuEdit.add(jSeparator3);

        jMenuItemPreferences.setText("Preferences");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPreferences);

        jMenuBar.add(jMenuEdit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colors, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneCuffs, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPaneCuffs, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addComponent(colors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateCuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateCuffActionPerformed
		CuffTab muddTab = (CuffTab) jTabbedPaneCuffs.getSelectedComponent();
		if (muddTab != null) {
			muddTab.add(new Cuff(colors));
		}
    }//GEN-LAST:event_jMenuItemCreateCuffActionPerformed

    private void jMenuItemCreateTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateTabActionPerformed
		jTabbedPaneCuffs.addTab("Tab " + (jTabbedPaneCuffs.getTabCount() + 1), new CuffTab());
		jTabbedPaneCuffs.setSelectedIndex(jTabbedPaneCuffs.getComponentCount() - 1);
    }//GEN-LAST:event_jMenuItemCreateTabActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
		Component cmp = jTabbedPaneCuffs.getSelectedComponent();
		if (cmp != null && cmp instanceof CuffTab) {
			CuffTab cuffTab = (CuffTab) cmp;
			if (cuffTab.getFilePath() == null) {
				jMenuItemSaveAsActionPerformed(evt);
			} else {
				saveToFile(cuffTab.getFilePath().toFile(), cuffTab);
			}
		}
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
		Component cmp = jTabbedPaneCuffs.getSelectedComponent();
		if (cmp != null && cmp instanceof CuffTab) {
			CuffTab cuffTab = (CuffTab) cmp;
			try {
				fileChooser.setCurrentDirectory(new File(PreferencesData.LAST_SAVE_LOCATION));
			} catch (Exception e) {
			}
			int option = fileChooser.showSaveDialog(this);
			if (option == JFileChooser.APPROVE_OPTION) {
				File theFileToSave = fileChooser.getSelectedFile();
				Path filePath = theFileToSave.toPath();
				if (!filePath.toString().endsWith(".xml")) {
					theFileToSave = new File(filePath + ".xml");
					filePath = theFileToSave.toPath();
				}
				saveToFile(theFileToSave, cuffTab);
				cuffTab.setFilePath(filePath);
				jTabbedPaneCuffs.setTitleAt(jTabbedPaneCuffs.getSelectedIndex(), filePath.getFileName().toString().split("\\.")[0]);
			}
		}
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
		try {
			fileChooser.setCurrentDirectory(new File(PreferencesData.LAST_SAVE_LOCATION));
		} catch (Exception e) {
		}
		int option = fileChooser.showOpenDialog(this);
		if (option == JFileChooser.APPROVE_OPTION) {
			try {
				File file = fileChooser.getSelectedFile();
				boolean alreadyOpen = false;
				CuffTab openTab = null;
				for (Component cmp : jTabbedPaneCuffs.getComponents()) {
					if (cmp instanceof CuffTab) {
						if (file.toPath().equals(((CuffTab) cmp).getFilePath())) {
							alreadyOpen = true;
							openTab = (CuffTab) cmp;
							break;
						}
					}
				}
				if (alreadyOpen) {
					int res = JOptionPane.showConfirmDialog(this, "That collection is already open, if you open it again you may loose unsaved data. Do you want to continue?");
					if (res == JOptionPane.OK_OPTION) {
						jTabbedPaneCuffs.remove(openTab);
					} else {
						return;
					}
				}
				Builder parser = new Builder();
				FileInputStream fis = new FileInputStream(file);
				Document doc = parser.build(fis);
				Element root = doc.getRootElement();
				CuffTab cuffTab = new CuffTab();
				cuffTab.load(root, colors);
				cuffTab.setFilePath(file.toPath());
				jTabbedPaneCuffs.addTab(file.toPath().getFileName().toString().split("\\.")[0], cuffTab);
				jTabbedPaneCuffs.setSelectedComponent(cuffTab);
				String path = file.toPath().toString();
				path = path.substring(0, path.lastIndexOf('\\'));
				PreferencesData.LAST_SAVE_LOCATION = path;
				PreferencesData.save();
			} catch (ParsingException | IOException ex) {
				Logger.getLogger(CuffMain.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
		jTabbedPaneCuffs.remove(jTabbedPaneCuffs.getSelectedComponent());
		jTabbedPaneCuffs.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
		System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
		Component cmp = jTabbedPaneCuffs.getSelectedComponent();
		if (cmp != null && cmp instanceof CuffTab) {
			CuffTab cTab = (CuffTab) cmp;
			cTab.undo();
		}
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedoActionPerformed
		Component cmp = jTabbedPaneCuffs.getSelectedComponent();
		if (cmp != null && cmp instanceof CuffTab) {
			CuffTab cTab = (CuffTab) cmp;
			cTab.redo();
		}
    }//GEN-LAST:event_jMenuItemRedoActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
		preferences.setVisible(true);
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CuffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				PreferencesData.load();
				new CuffMain().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.sleepyduck.Colors colors;
    private net.sleepyduck.CuffTab cuffTab1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemCreateCuff;
    private javax.swing.JMenuItem jMenuItemCreateTab;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPaneCuffs;
    // End of variables declaration//GEN-END:variables
}
