/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sleepyduck;

import java.awt.Component;
import java.nio.file.Path;
import nu.xom.Attribute;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author MetcalfPriv
 */
public class CuffTab extends javax.swing.JPanel {
	
	private Path filePath;

	/**
	 * Creates new form MuddTab
	 */
	public CuffTab() {
		initComponents();
	}
	
	public void add(Cuff cuff) {
		jPanelInner.add(cuff);
		validate();
	}
	
	public Element save() {
		Element root = new Element("CuffSet");
		for (Component cuff : jPanelInner.getComponents()) {
			if (cuff instanceof Cuff) {
				root.appendChild(((Cuff) cuff).getSaveData());
			}
		}
		return root;
	}
	
	void load(Element root, Colors colors) {
		Cuff cuff;
		Elements elements = root.getChildElements("Cuff");
		for (int i = 0; i < elements.size(); ++i) {
			cuff = new Cuff(colors);
			cuff.load(elements.get(i));
			add(cuff);
		}
	}
	
	public void setFilePath(Path path) {
		filePath = path;
	}
	
	public Path getFilePath() {
		return filePath;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanelInner = new javax.swing.JPanel();

        jPanelInner.setLayout(new net.sleepyduck.WrapLayout());
        jScrollPane.setViewportView(jPanelInner);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelInner;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
