/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sleepyduck;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;

/**
 *
 * @author MetcalfPriv
 */
public class EraseColor extends CuffColor {

	BufferedImage image;

	public EraseColor() throws IOException {
		super();
		setBackground(Color.WHITE);
	}

	@Override
	public void paint(Graphics graphics) {
		super.paint(graphics);
		graphics.setColor(Color.BLACK);
		int _width = PreferencesData.PALETTE_COLOR_SIZE / 10;
		int[] X1 = {_width, _width + _width, getWidth() - _width, getWidth() - _width, getWidth() - _width - _width, _width};
		int[] X2 = {getWidth() - _width, getWidth() - _width - _width, _width, _width, _width + _width, getWidth() - _width};
		int[] Y = {_width, _width, getHeight() - _width - _width, getHeight() - _width, getHeight() - _width, _width + _width};
		graphics.drawPolygon(X1, Y, Y.length);
		graphics.fillPolygon(X1, Y, Y.length);
		graphics.drawPolygon(X2, Y, Y.length);
		graphics.fillPolygon(X2, Y, Y.length);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
